ansible_user: ubuntu
ansible_ssh_private_key_file: /home/postegre/.ssh/id_rsa

# <-- ЗДЕСЬ МЕНЯЕТСЯ ТОЛЬКО ЭТО (скрипт обновит сам) -->
bastion_host: "158.160.33.169"

# Общая строка для ProxyJump на ВНУТРЕННИЕ хосты
ssh_common_args: >-
  -o ProxyJump={{ ansible_user }}@{{ bastion_host }}
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o ServerAliveInterval=60
  -o ServerAliveCountMax=3
