---
# === INSTALL & SYSTEM PREP ===
- name: Copy elasticsearch deb package
  ansible.builtin.copy:
    src: "{{ elasticsearch_deb_src }}"
    dest: /tmp/elasticsearch.deb
    mode: "0644"
  when: elasticsearch_deb_src is defined
  tags: [elasticsearch]

- name: Install elasticsearch from local deb (offline)
  ansible.builtin.apt:
    deb: /tmp/elasticsearch.deb
    state: present
  when: elasticsearch_deb_src is defined
  tags: [elasticsearch]

- name: Ensure vm.max_map_count is sufficient
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: true
  tags: [elasticsearch]

- name: Check if any swap is active
  ansible.builtin.command: bash -lc "swapon --summary | tail -n +2 | cat"
  register: swap_summary
  changed_when: false
  tags: [elasticsearch]

- name: Disable all swap if active
  ansible.builtin.command: swapoff -a
  when: swap_summary.stdout != ""
  tags: [elasticsearch]

- name: Persistently disable swap in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^\s*(.+\s+swap\s+.+)$'
    replace: '# \1'
  tags: [elasticsearch]

- name: Set vm.swappiness very low
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "1"
    state: present
    reload: true
  tags: [elasticsearch]

- name: Ensure systemd override dir exists
  ansible.builtin.file:
    path: /etc/systemd/system/elasticsearch.service.d
    state: directory
    mode: "0755"
  tags: [elasticsearch]

- name: Configure systemd limits and restart policy
  ansible.builtin.copy:
    dest: /etc/systemd/system/elasticsearch.service.d/override.conf
    mode: "0644"
    content: |
      [Service]
      LimitMEMLOCK=infinity
      LimitNOFILE=65536
      Restart=always
      RestartSec=5
  notify: Restart elasticsearch
  tags: [elasticsearch]

- name: Ensure data dir exists and owned by elasticsearch
  ansible.builtin.file:
    path: /var/lib/elasticsearch
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: "0750"
  tags: [elasticsearch]

- name: Ensure log dir exists and owned by elasticsearch
  ansible.builtin.file:
    path: /var/log/elasticsearch
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: "0755"
  tags: [elasticsearch]

# === CONFIG ===
- name: Deploy elasticsearch.yml
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: "0640"
  notify: Restart elasticsearch
  tags: [elasticsearch_config]

# Защита от «хвостов» secure_password в yml
- name: Comment out leftover keystore/truststore secure_password lines (defensive)
  ansible.builtin.replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^(xpack\.security\.transport\.ssl\.(?:keystore|truststore)\.secure_password\s*:\s*.*)$'
    replace: '# \1'
  register: es_keystore_pw_cleanup
  changed_when: es_keystore_pw_cleanup is changed
  notify: Restart elasticsearch
  tags: [elasticsearch_config]

- name: Ensure jvm.options.d dir exists
  ansible.builtin.file:
    path: /etc/elasticsearch/jvm.options.d
    state: directory
    mode: "0755"
  tags: [elasticsearch]

- name: Deploy heap.options
  ansible.builtin.template:
    src: heap.options.j2
    dest: /etc/elasticsearch/jvm.options.d/heap.options
    owner: root
    group: root
    mode: "0644"
  notify: Restart elasticsearch
  tags: [elasticsearch_config]

- name: Enable and start elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    state: started
    daemon_reload: true
  tags: [elasticsearch]

- name: Flush handlers (restart elasticsearch if notified)
  ansible.builtin.meta: flush_handlers
  tags: [elasticsearch_config, elasticsearch]

# === CHECKS ===
- name: Wait for port 9200 to listen
  ansible.builtin.wait_for:
    host: "127.0.0.1"
    port: "{{ elasticsearch_http_port | default(9200) }}"
    state: started
    delay: 2
    timeout: 90
  tags: [elasticsearch_check]

- name: HTTP check Elasticsearch endpoint
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ elasticsearch_http_port | default(9200) }}/"
    return_content: yes
    status_code: 200
  register: es_root
  retries: 10
  delay: 3
  until: es_root is succeeded and es_root.status == 200
  tags: [elasticsearch_check]
